apiVersion: v1
kind: Service
metadata:
    name: svc-test
    labels:
        app: test
spec:
    ports:
    - port: 100
      protocol: TCP
      targetPort: 100
    selector:
        app: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-test
  labels:
      app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: samoyedsun/test-python:v2
        env:
        - name: REQUEST_URL
          value: "http://svc-probe:4000"
        - name: THREAD_NUM
          value: "100"
