apiVersion: v1
kind: Service
metadata:
    name: svc-consumer
    labels:
        app: consumer
spec:
    ports:
    - port: 100
      targetPort: 100
    selector:
        app: consumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-consumer
  labels:
      app: consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: samoyedsun/bid-dev:v3
        command: ["./bin/artisan"]
        args: ["queue:work", "--tries=3"]