apiVersion: v1
kind: Service
metadata:
    name: svc-crontab
    labels:
        app: crontab
spec:
    ports:
    - port: 100
      targetPort: 100
    selector:
        app: crontab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-crontab
  labels:
      app: crontab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crontab
  template:
    metadata:
      labels:
        app: crontab
    spec:
      containers:
      - name: crontab
        image: samoyedsun/bid-dev:v3
        command: ["crond"]
        args: ["-n"]