apiVersion: v1
kind: Service
metadata:
    name: svc-frontend
    labels:
        app: frontend
spec:
    type: NodePort 
    #    externalIPs:
    #- 18.212.128.104
    ports:
    - port: 80
      protocol: TCP
      targetPort: fted-server
      nodePort: 30000
    selector:
        app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-frontend
  labels:
      app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: samoyedsun/papa-dev:latest        
        env:
        - name: API_HOST
          value: svc-backend-proxy
        - name: NODE_ENV
          value: dev
        ports:
        - name: fted-server
          containerPort: 80
