apiVersion: v1
kind: Service                       # 部署方式
metadata:                           # 该资源的元数据
    name: svc-mysql                 # 资源名，必须的元数据
    labels:                         # 待了解
        app: mysql
spec:                               # 资源的规格
    ports:                          # 端口信息
    - port: 3306                    # svc入口
      targetPort: mysql-server      # svc出口，指向pod
    selector:                       # 待了解
        app: mysql
---
apiVersion: apps/v1
kind: Deployment                    # 部署方式
metadata:                           # 该资源的元数据
  name: dp-mysql                    # 资源名，必须的元数据
  labels:                           # 待了解
      app: mysql
spec:                               # 资源的规格
  replicas: 1                       # 副本数量
  selector:                         # 待了解
    matchLabels:
      app: mysql
  template:                         # 定义pod的模版 (重要部分)
    metadata:                       # 该pod的元数据, 至少定义一个label，可以随笔指定.
      labels:                       # 待了解
        app: mysql
    spec:                           # pod的规格
      containers:
      - name: mysql                 # 名字
        image: mysql:5.7            # 镜像
        env:                        # 环境变量
        - name: MYSQL_USER
          value: bid
        - name: MYSQL_PASSWORD
          value: lyZMD8HKeMe6Gz
        - name: MYSQL_ROOT_PASSWORD
          value: lyZMD8HKeMe6Gz
        - name: MYSQL_DATABASE
          value: bid  
        ports:                      # 向svc开放的端口
        - name: mysql-server
          containerPort: 3306
