#!/usr/bin/python

import socket, sys

RECV_LEN = 1024

HOST = sys.argv[1]
PORT = int(sys.argv[2])

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM, socket.SOL_TCP)
s.connect((HOST, PORT))
s.send(b'*3\r\n$3\r\nSET\r\n$10\r\nprobeRedis\r\n$10\r\nhelloRedis\r\n')
ra = s.recv(RECV_LEN)
s.close()

print(ra)
